DROP DATABASE IF EXISTS exampledb;
CREATE DATABASE exampledb;

DROP DATABASE IF EXISTS testdb;
CREATE DATABASE testdb;

DROP DATABASE IF EXISTS recipe_db;
CREATE DATABASE recipe_db;

DROP DATABASE IF EXISTS dbFood;
CREATE DATABASE dbFood;
